name: 🧪 CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: 🔬 Test Suite
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🔍 Type checking
      run: npx tsc --noEmit --skipLibCheck
      
    - name: 🧹 Lint code  
      run: |
        if [ ! -f .eslintrc.json ]; then
          echo "ESLint not configured, skipping lint check"
        else
          npm run lint
        fi
      
    - name: 🧪 Run all tests
      run: node run-tests.js
      
    - name: 🏗️ Test build
      run: |
        export NEXT_TELEMETRY_DISABLED=1
        npm run build

  test-categories:
    name: 📊 Test Categories
    runs-on: ubuntu-latest
    needs: test
    
    strategy:
      matrix:
        test-category: [unit, integration, performance, debug]
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🧪 Run ${{ matrix.test-category }} tests
      run: node run-tests.js ${{ matrix.test-category }}

  build-test:
    name: 🏗️ Build Test
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🏗️ Build application
      run: npm run build
      
    - name: 📤 Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: .next/
        retention-days: 1

  performance:
    name: ⚡ Performance Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: ⚡ Run performance tests
      run: node run-tests.js performance
      
    - name: 📊 Performance report
      run: |
        echo "## ⚡ Performance Test Results" >> $GITHUB_STEP_SUMMARY
        echo "Performance tests completed successfully!" >> $GITHUB_STEP_SUMMARY
        echo "- WebWorker stress test: ✅ PASSED" >> $GITHUB_STEP_SUMMARY
        echo "- Memory efficiency: ✅ PASSED" >> $GITHUB_STEP_SUMMARY
        echo "- Processing speed: ✅ PASSED" >> $GITHUB_STEP_SUMMARY

  status-check:
    name: ✅ Status Check
    runs-on: ubuntu-latest
    needs: [test, test-categories, build-test, performance]
    if: always()
    
    steps:
    - name: 📊 Check all jobs status
      run: |
        echo "## 🎯 CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
        echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Test Suite | ${{ needs.test.result == 'success' && '✅ PASSED' || '❌ FAILED' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Test Categories | ${{ needs.test-categories.result == 'success' && '✅ PASSED' || '❌ FAILED' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Build Test | ${{ needs.build-test.result == 'success' && '✅ PASSED' || '❌ FAILED' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Performance | ${{ needs.performance.result == 'success' && '✅ PASSED' || '❌ FAILED' }} |" >> $GITHUB_STEP_SUMMARY
        
    - name: ❌ Fail if any job failed
      if: contains(needs.*.result, 'failure')
      run: exit 1